// Private London dental clinic data
// Last updated: 2025-12-18 10:09:11
// Total clinics: 48
// Source: OpenStreetMap (Free)
export const clinicsData = [
  {
    "name": "Private Central London Dentist",
    "address": "55, Wimpole Street, City of Westminster, W1G 8DQ",
    "phone": null,
    "link": null,
    "postcode": "W1G 8DQ",
    "area": "Marylebone",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Rayden's Dentist",
    "address": "Upminster Road South, Greater London, RM13 9AG",
    "phone": null,
    "link": null,
    "postcode": "RM13 9AG",
    "area": "Rainham",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "The Wimbledon Dentist",
    "address": "Merton Road, Greater London, SW19 1EJ",
    "phone": null,
    "link": null,
    "postcode": "SW19 1EJ",
    "area": "Merton",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Kirby's Pharmacy & Dentist",
    "address": "High Street, Greater London, TW11 8HG",
    "phone": null,
    "link": null,
    "postcode": "TW11 8HG",
    "area": "Strawberry Hill",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "The Dentist",
    "address": "130, Putney High Street, Greater London, SW15 1RG",
    "phone": null,
    "link": null,
    "postcode": "SW15 1RG",
    "area": "Putney",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Elizabeth Street Dentist",
    "address": "85, Elizabeth Street, City of Westminster, SW1W 9PD",
    "phone": null,
    "link": null,
    "postcode": "SW1W 9PD",
    "area": "Belgravia",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Maidavale Dentist",
    "address": "10, Quex Road, Greater London, NW6 4PL",
    "phone": "+44 20 7624 4302",
    "link": "https://maidavaledentist.co.uk/",
    "postcode": "NW6 4PL",
    "area": "Kilburn",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Toothbeary - My Child's Dentist",
    "address": "358a, Richmond Road, Greater London, TW1 2DU",
    "phone": "+44 20 8831 6870",
    "link": "https://www.toothbearykids.co.uk/",
    "postcode": "TW1 2DU",
    "area": "St Margarets",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Dentist @ W2",
    "address": "3-4, Norfolk Place, City of Westminster, W2 1QN",
    "phone": "+44 20 7402 4024",
    "link": "https://www.dentistw2.co.uk/",
    "postcode": "W2 1QN",
    "area": "Paddington",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Perfect Smile Dentist",
    "address": "50, Ashburnham Road, Greater London, TW10 7NF",
    "phone": "+44 20 8948 1675",
    "link": "https://www.perfectsmile-dental.com/dentist-richmond-ham.htm",
    "postcode": "TW10 7NF",
    "area": "Ham",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "The Old Dentist",
    "address": "33, Chatsworth Road, Greater London, E5 0LH",
    "phone": null,
    "link": null,
    "postcode": "E5 0LH",
    "area": "Homerton",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "The Haringey Dentist",
    "address": "16, Green Lanes, City of London, N4 1LA",
    "phone": null,
    "link": "https://theharingeydentist.com",
    "postcode": "N4 1LA",
    "area": "Harringay",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Dental Practice of Cosmetic Dentist",
    "address": "77, Harley Street, City of Westminster, W1G 7HS",
    "phone": null,
    "link": "https://www.77harleystreet.co.uk/",
    "postcode": "W1G 7HS",
    "area": "Marylebone",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Inglehurst Dentist Practice",
    "address": "51, Redbridge Lane East, Greater London, IG4 5EY",
    "phone": "+44 20 8551 3550",
    "link": null,
    "postcode": "IG4 5EY",
    "area": "Redbridge",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": "Mo-Fr 09:00-13:00,14:00-17:00; Sa-Su off"
  },
  {
    "name": "Winning Smiles Dentist",
    "address": "1, Colchester Road, Greater London, RM3 0AQ",
    "phone": "+44 1708 241900",
    "link": "https://winning-smiles.co.uk/",
    "postcode": "RM3 0AQ",
    "area": "Harold Wood",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": "Mo,Tu 09:00-19:00; We 08:00-18:00; Th 08:00-17:00; Fr 08:00-16:00; Sa 8:30-12:30"
  },
  {
    "name": "{my} dentist",
    "address": "392, Edgware Road, City of Westminster, W2 1DR",
    "phone": null,
    "link": "https://www.mydentist.co.uk/dentists/practices/england/london/westminster/392-edgware-road",
    "postcode": "W2 1DR",
    "area": "Paddington",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "The Modern Dentist",
    "address": "1-3, Leonard Street, Greater London, EC2A 4AQ",
    "phone": null,
    "link": null,
    "postcode": "EC2A 4AQ",
    "area": "Finsbury",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Dentist By The Green",
    "address": "25, Denmark Hill, Greater London, SE5 8RT",
    "phone": null,
    "link": "https://dentistbythegreen.co.uk/",
    "postcode": "SE5 8RT",
    "area": "Camberwell",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Imperial College Dentist",
    "address": "Exhibition Road, City of Westminster, SW7 2AZ",
    "phone": null,
    "link": null,
    "postcode": "SW7 2AZ",
    "area": "Knightsbridge",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": "Mo-Th 08:00-20:00; Fr 08:00-20:00; Sa 09:00-17:00"
  },
  {
    "name": "My E20 Dentist",
    "address": "27, Villiers Gardens, Greater London, E20 1GW",
    "phone": null,
    "link": null,
    "postcode": "E20 1GW",
    "area": "Stratford",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": "Mo-Sa 09:00-21:00"
  },
  {
    "name": "Quality Smile Dentist",
    "address": "71, Bromley Road, Greater London, SE6 2UA",
    "phone": "+44 20 8698 7097",
    "link": "http://www.qualitysmilecare.co.uk/aboutus.php",
    "postcode": "SE6 2UA",
    "area": "Southend",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Sofia House dentist",
    "address": "129c, Seaforth Avenue, Greater London, KT3 6JU",
    "phone": null,
    "link": null,
    "postcode": "KT3 6JU",
    "area": "West Barnes",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "121 Dentist",
    "address": "121, Burlington Road, Greater London, KT3 4AW",
    "phone": null,
    "link": null,
    "postcode": "KT3 4AW",
    "area": "Motspur Park",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Dentist & Hygienist",
    "address": "Kentish Town Road, Greater London, NW5 2EN",
    "phone": "+44 20 7267 7653",
    "link": null,
    "postcode": "NW5 2EN",
    "area": "Kentish Town",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "The Gentle Dentist",
    "address": "61, Shelton Street, Greater London, WC2H 9HE",
    "phone": null,
    "link": null,
    "postcode": "WC2H 9HE",
    "area": "Greater London",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "The Kensington Dentist",
    "address": "117, Kensington Church Street, Greater London, W8 4BY",
    "phone": "+44 20 7221 1680",
    "link": "https://www.thekensingtondentist.com/",
    "postcode": "W8 4BY",
    "area": "Kensington",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Banning dentist",
    "address": "The Highway, Greater London, E1W 2AQ",
    "phone": null,
    "link": null,
    "postcode": "E1W 2AQ",
    "area": "Wapping",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": "Mo,We 09:00-20:00; Tu,Th 08:00-17:00; Fr,Sa 09:00-17:00; Su 10:00-14:00"
  },
  {
    "name": "The Richmond Dentist",
    "address": "Water Lane, Greater London, TW9 1TJ",
    "phone": null,
    "link": null,
    "postcode": "TW9 1TJ",
    "area": "St Margarets",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Glow Dentist",
    "address": "87, Northcote Road, Greater London, SW11 6PW",
    "phone": null,
    "link": "https://www.glowdental.co.uk/",
    "postcode": "SW11 6PW",
    "area": "Clapham Junction",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "The Finchley Dentist",
    "address": "26, Southern Road, Greater London, N2 9JG",
    "phone": "+44 20 3488 0335",
    "link": "https://www.thefinchleydentist.com/",
    "postcode": "N2 9JG",
    "area": "Muswell Hill",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Kensington Dentist",
    "address": "4, Wrights Lane, Greater London, W8 5SW",
    "phone": null,
    "link": "http://kensington-dentist.com/",
    "postcode": "W8 5SW",
    "area": "Kensington",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "New Kings Road Dentist",
    "address": "New King's Road, Greater London, SW6 4SE",
    "phone": null,
    "link": null,
    "postcode": "SW6 4SE",
    "area": "Fulham",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "John Lott Dentist",
    "address": "735, Wonderland Road North, London, N6H 4L1",
    "phone": "+1-519-657-6767",
    "link": "http://www.thetoothteam.com",
    "postcode": "N6H 4L1",
    "area": "London",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "LightHouse Dental London",
    "address": "1850, Adelaide Street North, London, N5X 4B7",
    "phone": "+1-519-964-8888",
    "link": "https://london.lighthousedental.ca/",
    "postcode": "N5X 4B7",
    "area": "London",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": "Mo-Su 09:00-20:00"
  },
  {
    "name": "Westminster House Dental Practice",
    "address": "11-13, Horseferry Road, City of Westminster, SW1P 2AH",
    "phone": "+44 20 7976 5251",
    "link": "https://rodericksdentalpartners.co.uk/our-practices/westminster-house-dental-practice",
    "postcode": "SW1P 2AH",
    "area": "Millbank",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": "Mo-Th 08:00-20:00; Fr 08:00-18:30; Sa 09:00-13:00"
  },
  {
    "name": "Camden Dental Centre",
    "address": "Camden High Street, Greater London, NW1 0LT",
    "phone": "+44 20 7380 0768",
    "link": null,
    "postcode": "NW1 0LT",
    "area": "Chalk Farm",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Bond Dental London (Kensington)",
    "address": "151, North End Road, Greater London, W14 9NH",
    "phone": null,
    "link": "https://www.bonddental.co.uk/kensington/",
    "postcode": "W14 9NH",
    "area": "West Kensington",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "The Kensington Orthodontic Clinic",
    "address": "6-8, Netherwood Road, Greater London, W14 0BL",
    "phone": null,
    "link": null,
    "postcode": "W14 0BL",
    "area": "Brook Green",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Kensington Olympia Dental Clinic",
    "address": "4, Maclise Road, Greater London, W14 0JZ",
    "phone": "+44 20 7602 7569",
    "link": null,
    "postcode": "W14 0JZ",
    "area": "Brook Green",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Kensington Dental Practice",
    "address": "129-131, Kensington High Street, Greater London, W8 5SF",
    "phone": null,
    "link": "https://kensingtondental.co.uk/",
    "postcode": "W8 5SF",
    "area": "Kensington",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Kensington Health Clinic",
    "address": "4, Victoria Grove, Greater London, SW7 4QU",
    "phone": "+44 20 7589 9990",
    "link": "https://www.kensingtonhealthclinic.co.uk/",
    "postcode": "SW7 4QU",
    "area": "South Kensington",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Chelsea Dental Spa",
    "address": "273, Old Brompton Road, Greater London, SW5 9JA",
    "phone": "+44 20 7244 1199",
    "link": "https://chelseadentalspa.co.uk/",
    "postcode": "SW5 9JA",
    "area": "Earl's Court",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": "Mo-Fr 09:00-19:30; Sa 10:00-17:30"
  },
  {
    "name": "Chelsea Dental Clinic",
    "address": "298, Fulham Road, Greater London, SW10 9EP",
    "phone": "+44 20 7349 8889",
    "link": "https://www.chelseadentalclinic.co.uk/",
    "postcode": "SW10 9EP",
    "area": "Brompton",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Happy Kids Dental Chelsea",
    "address": "18, Cadogan Gardens, Greater London, SW3 2RP",
    "phone": "+44 20 7078 0822",
    "link": "https://happykidsdental.co.uk/",
    "postcode": "SW3 2RP",
    "area": "Chelsea",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Chelsea Dental Lounge",
    "address": "18, Cadogan Gardens, Greater London, SW3 2RB",
    "phone": "+44 20 7581 6161",
    "link": "http://chelseadentalgroup.co.uk/",
    "postcode": "SW3 2RB",
    "area": "Chelsea",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Chelsea Dental Studio",
    "address": "295, King's Road, Greater London, SW3 5UR",
    "phone": null,
    "link": "https://chelseadentalstudio.co.uk",
    "postcode": "SW3 5UR",
    "area": "Chelsea",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Islington Smiles",
    "address": "246, Upper Street, Greater London, N1 1RU",
    "phone": null,
    "link": null,
    "postcode": "N1 1RU",
    "area": "Highbury",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": null
  },
  {
    "name": "Dental Beauty Islington",
    "address": "103-104, Upper Street, Greater London, N1 1QN",
    "phone": "+44 20 7359 6103",
    "link": "https://dentalbeautyislington.co.uk/",
    "postcode": "N1 1QN",
    "area": "Islington",
    "services": [],
    "languages": [
      "English"
    ],
    "source": "OpenStreetMap (Free)",
    "private": true,
    "nhs": false,
    "emergency": false,
    "children": false,
    "wheelchair_access": false,
    "parking": false,
    "rating": null,
    "opening_hours": "Mo-Fr 09:00-12:30, 14:00-17:30; Sa 09:00-13:30"
  }
];
