// Sample dental clinic data - embedded in frontend for reliability
export const clinicsData = [
  {
    name: "Smile Dental Care - Central London",
    address: "123 Oxford Street, London W1D 2HX",
    phone: "020 7123 4567",
    services: ["General Dentistry", "Teeth Whitening", "Dental Implants", "Root Canal Treatment"],
    languages: ["English", "Spanish", "French"],
    link: "https://example-dental-1.co.uk",
    source: "Sample Data",
    area: "Central London",
    postcode: "W1D 2HX",
    nhs: true,
    private: true,
    emergency: true,
    children: true,
    wheelchair_access: true,
    parking: false,
    rating: 4.5,
    opening_hours: "Mon-Fri: 9am-6pm, Sat: 10am-4pm"
  },
  {
    name: "Bright Smiles Clinic - Camden",
    address: "45 Camden High Street, London NW1 7JE",
    phone: "020 7387 8901",
    services: ["Orthodontics", "Cosmetic Dentistry", "General Dentistry", "Teeth Whitening"],
    languages: ["English", "Polish", "Arabic"],
    link: "https://example-dental-2.co.uk",
    source: "Sample Data",
    area: "Camden",
    postcode: "NW1 7JE",
    nhs: false,
    private: true,
    emergency: false,
    children: true,
    wheelchair_access: true,
    parking: true,
    rating: 4.8,
    opening_hours: "Mon-Thu: 8am-7pm, Fri: 8am-5pm"
  },
  {
    name: "Family Dental Practice - Islington",
    address: "78 Upper Street, London N1 0NP",
    phone: "020 7359 2345",
    services: ["General Dentistry", "Children's Dentistry", "Emergency Care", "Preventive Care"],
    languages: ["English", "Turkish", "Greek"],
    link: "https://example-dental-3.co.uk",
    source: "Sample Data",
    area: "Islington",
    postcode: "N1 0NP",
    nhs: true,
    private: false,
    emergency: true,
    children: true,
    wheelchair_access: false,
    parking: false,
    rating: 4.2,
    opening_hours: "Mon-Fri: 8am-6pm, Sat: 9am-1pm"
  },
  {
    name: "Westminster Dental Centre",
    address: "12 Victoria Street, London SW1H 0TL",
    phone: "020 7222 3456",
    services: ["General Dentistry", "Dental Implants", "Periodontics", "Oral Surgery"],
    languages: ["English", "Mandarin", "Cantonese"],
    link: "https://example-dental-4.co.uk",
    source: "Sample Data",
    area: "Westminster",
    postcode: "SW1H 0TL",
    nhs: true,
    private: true,
    emergency: true,
    children: false,
    wheelchair_access: true,
    parking: true,
    rating: 4.7,
    opening_hours: "Mon-Fri: 9am-5:30pm"
  },
  {
    name: "Greenwich Dental Care",
    address: "56 Greenwich High Road, London SE10 8JL",
    phone: "020 8858 9012",
    services: ["General Dentistry", "Orthodontics", "Teeth Whitening", "Dental Hygiene"],
    languages: ["English", "Portuguese", "Spanish"],
    link: "https://example-dental-5.co.uk",
    source: "Sample Data",
    area: "Greenwich",
    postcode: "SE10 8JL",
    nhs: true,
    private: true,
    emergency: false,
    children: true,
    wheelchair_access: true,
    parking: true,
    rating: 4.4,
    opening_hours: "Mon-Wed: 9am-6pm, Thu-Fri: 9am-7pm, Sat: 10am-3pm"
  },
  {
    name: "Hackney Smile Studio",
    address: "89 Mare Street, London E8 4GH",
    phone: "020 8985 6789",
    services: ["Cosmetic Dentistry", "Teeth Whitening", "Veneers", "General Dentistry"],
    languages: ["English", "Bengali", "Urdu"],
    link: "https://example-dental-6.co.uk",
    source: "Sample Data",
    area: "Hackney",
    postcode: "E8 4GH",
    nhs: false,
    private: true,
    emergency: false,
    children: false,
    wheelchair_access: false,
    parking: false,
    rating: 4.6,
    opening_hours: "Tue-Sat: 10am-6pm"
  },
  {
    name: "Tower Hamlets Dental Surgery",
    address: "234 Commercial Road, London E1 1BB",
    phone: "020 7790 1234",
    services: ["General Dentistry", "Emergency Care", "Children's Dentistry", "Preventive Care"],
    languages: ["English", "Bengali", "Hindi", "Urdu"],
    link: "https://example-dental-7.co.uk",
    source: "Sample Data",
    area: "Tower Hamlets",
    postcode: "E1 1BB",
    nhs: true,
    private: false,
    emergency: true,
    children: true,
    wheelchair_access: true,
    parking: false,
    rating: 4.1,
    opening_hours: "Mon-Fri: 8am-7pm, Sat: 9am-2pm"
  },
  {
    name: "Kensington Dental Practice",
    address: "156 Kensington High Street, London W8 6SH",
    phone: "020 7937 5678",
    services: ["General Dentistry", "Dental Implants", "Cosmetic Dentistry", "Teeth Whitening", "Orthodontics"],
    languages: ["English", "French", "Italian"],
    link: "https://example-dental-8.co.uk",
    source: "Sample Data",
    area: "Kensington",
    postcode: "W8 6SH",
    nhs: false,
    private: true,
    emergency: true,
    children: true,
    wheelchair_access: true,
    parking: true,
    rating: 4.9,
    opening_hours: "Mon-Fri: 8am-6pm, Sat: 9am-4pm"
  },
  {
    name: "Maida Vale Orthodontics",
    address: "78 Maida Vale, London NW6 1AE",
    phone: "020 7289 1234",
    services: ["Orthodontics", "General Dentistry", "Teeth Whitening", "Braces"],
    languages: ["English", "French", "Spanish"],
    link: "https://example-dental-9.co.uk",
    source: "Sample Data",
    area: "Maida Vale",
    postcode: "NW6 1AE",
    nhs: true,
    private: true,
    emergency: false,
    children: true,
    wheelchair_access: true,
    parking: true,
    rating: 4.7,
    opening_hours: "Mon-Fri: 9am-6pm, Sat: 10am-2pm"
  }
];

