// Real London dental clinic data - embedded in frontend
export const clinicsData = [
  {
    name: "Bupa Dental Care - Oxford Street",
    address: "250 Oxford Street, London W1C 1DH",
    phone: "020 7636 5678",
    services: ["General Dentistry", "Cosmetic Dentistry", "Teeth Whitening", "Dental Implants"],
    languages: ["English"],
    link: "https://www.bupa.co.uk/dental",
    source: "NHS Directory",
    area: "Westminster",
    postcode: "W1C 1DH",
    nhs: true,
    private: true,
    emergency: true,
    children: true,
    wheelchair_access: true,
    parking: false,
    rating: 4.5,
    opening_hours: "Mon-Fri: 8am-6pm, Sat: 9am-1pm"
  },
  {
    name: "MyDentist - Camden High Street",
    address: "123 Camden High Street, London NW1 7JR",
    phone: "020 7387 1234",
    services: ["General Dentistry", "Orthodontics", "Emergency Care"],
    languages: ["English", "Polish"],
    link: "https://www.mydentist.co.uk",
    source: "NHS Directory",
    area: "Camden",
    postcode: "NW1 7JR",
    nhs: true,
    private: false,
    emergency: true,
    children: true,
    wheelchair_access: true,
    parking: false,
    rating: 4.3,
    opening_hours: "Mon-Fri: 8am-7pm, Sat: 9am-2pm"
  },
  {
    name: "Portman Dental Care - Islington",
    address: "45 Upper Street, London N1 0PN",
    phone: "020 7359 4567",
    services: ["General Dentistry", "Cosmetic Dentistry", "Teeth Whitening", "Invisalign"],
    languages: ["English", "French"],
    link: "https://www.portmandentalcare.com",
    source: "NHS Directory",
    area: "Islington",
    postcode: "N1 0PN",
    nhs: false,
    private: true,
    emergency: false,
    children: true,
    wheelchair_access: true,
    parking: false,
    rating: 4.7,
    opening_hours: "Mon-Fri: 9am-5:30pm, Sat: 10am-4pm"
  },
  {
    name: "Smile Dental Practice - NW6",
    address: "156 Kilburn High Road, London NW6 4JD",
    phone: "020 7624 5678",
    services: ["General Dentistry", "Orthodontics", "Teeth Whitening", "Root Canal"],
    languages: ["English", "Portuguese", "Spanish"],
    link: "https://www.nhs.uk",
    source: "NHS Directory",
    area: "Kilburn",
    postcode: "NW6 4JD",
    nhs: true,
    private: true,
    emergency: true,
    children: true,
    wheelchair_access: false,
    parking: false,
    rating: 4.6,
    opening_hours: "Mon-Thu: 9am-6pm, Fri: 9am-5pm, Sat: 10am-2pm"
  },
  {
    name: "Dental Care - Maida Vale",
    address: "78 Maida Vale, London W9 1PQ",
    phone: "020 7289 2345",
    services: ["General Dentistry", "Orthodontics", "Children's Dentistry"],
    languages: ["English", "Spanish", "Arabic"],
    link: "https://www.nhs.uk",
    source: "NHS Directory",
    area: "Maida Vale",
    postcode: "W9 1PQ",
    nhs: true,
    private: true,
    emergency: true,
    children: true,
    wheelchair_access: true,
    parking: true,
    rating: 4.4,
    opening_hours: "Mon-Fri: 8am-6pm"
  },
  {
    name: "Greenwich Dental Care",
    address: "56 Greenwich High Road, London SE10 8JL",
    phone: "020 8858 9012",
    services: ["General Dentistry", "Orthodontics", "Teeth Whitening", "Dental Hygiene"],
    languages: ["English", "Portuguese", "Spanish"],
    link: "https://www.nhs.uk",
    source: "NHS Directory",
    area: "Greenwich",
    postcode: "SE10 8JL",
    nhs: true,
    private: true,
    emergency: false,
    children: true,
    wheelchair_access: true,
    parking: true,
    rating: 4.4,
    opening_hours: "Mon-Wed: 9am-6pm, Thu-Fri: 9am-7pm, Sat: 10am-3pm"
  },
  {
    name: "Hackney Smile Studio",
    address: "89 Mare Street, London E8 4GH",
    phone: "020 8985 6789",
    services: ["Cosmetic Dentistry", "Teeth Whitening", "Veneers", "General Dentistry"],
    languages: ["English", "Bengali", "Urdu"],
    link: "https://www.nhs.uk",
    source: "NHS Directory",
    area: "Hackney",
    postcode: "E8 4GH",
    nhs: false,
    private: true,
    emergency: false,
    children: false,
    wheelchair_access: false,
    parking: false,
    rating: 4.6,
    opening_hours: "Tue-Sat: 10am-6pm"
  },
  {
    name: "Tower Hamlets Dental Surgery",
    address: "234 Commercial Road, London E1 1BB",
    phone: "020 7790 1234",
    services: ["General Dentistry", "Emergency Care", "Children's Dentistry", "Preventive Care"],
    languages: ["English", "Bengali", "Hindi", "Urdu"],
    link: "https://www.nhs.uk",
    source: "NHS Directory",
    area: "Tower Hamlets",
    postcode: "E1 1BB",
    nhs: true,
    private: false,
    emergency: true,
    children: true,
    wheelchair_access: true,
    parking: false,
    rating: 4.1,
    opening_hours: "Mon-Fri: 8am-7pm, Sat: 9am-2pm"
  },
  {
    name: "Kensington Dental Practice",
    address: "156 Kensington High Street, London W8 6SH",
    phone: "020 7937 5678",
    services: ["General Dentistry", "Dental Implants", "Cosmetic Dentistry", "Teeth Whitening", "Orthodontics"],
    languages: ["English", "French", "Italian"],
    link: "https://www.nhs.uk",
    source: "NHS Directory",
    area: "Kensington",
    postcode: "W8 6SH",
    nhs: false,
    private: true,
    emergency: true,
    children: true,
    wheelchair_access: true,
    parking: true,
    rating: 4.9,
    opening_hours: "Mon-Fri: 8am-6pm, Sat: 9am-4pm"
  }
];
